apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h07bi3457-nodejs-gitops
  description: This is GitOps manifest for h07bi3457-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=h07bi3457-nodejs
    backstage.io/kubernetes-id: h07bi3457-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: h07bi3457-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h07bi3457-nodejs
