apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h07bi3457-nodejs
  janus-idp.io/tekton: h07bi3457-nodejs
  backstage.io/kubernetes-id: h07bi3457-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h07bi3457-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
